### ISSUE TITLE
Generating static files

### ISSUE THREAD

**Issue by dvidsilva** [vikpe/react-webpack-babel-starter#2]
Hi, thanks for the project, huge time saver. 

Wondering if you have some suggestions for static site rendering, I tried different webpack plugins but no luck so far.

**Comment by vikpe** [comment]
@dvidsilva Thank you!

Do you mean static site rendering as in e.g. a blog with lots of posts? Please describe your use case.

**Comment by dvidsilva** [comment]
Hi, @vikpe  yes, I would like to pre-render the site so that it can be uploaded to s3 or something like that and served faster, so it doesn't have to get rendered on the client. Our data is not changing so we don't need it to be dynamic.  I got pretty far using this webpack plugin, but I'm still having errors at some point when I try to import other components. 

https://github.com/donskov/static-render-html-webpack-plugin

Thanks!

**Comment by vikpe** [comment]
You should be able to run `npm run build` and then upload the contents from `/dist/` to S3 or similar.

I use [GitHub Pages](https://pages.github.com/) for all my static sites at the moment. I haven't tried any react/webpack plugins.
