### ISSUE TITLE
Route + main.js

### ISSUE THREAD

**Issue by ivanJoly** [vikpe/react-webpack-babel-starter#4]
First off all, thanks for the great starter repo.
I don’t now if it’s a issue or I don’t now how it use it but when I use ‘React-router-dom’
And add routs like (in dev mode)

`<Route path="/home/:id" exact={true} component={Home} />`

Doesn’t work and lost the route of main.js
If I add this in dev.js in the webpack folder, works.

`    output: {
        publicPath: '/'
    },
    devServer: {
        hot: true, // enable HMR on the server
        historyApiFallback: true
    },`

I don’t now if this broke other things.
Sorry for my English
Thank you!

**Comment by vikpe** [comment]
@ivanJoly thank you for the notice.

I'll give it a try and update the repo asap.

**Comment by vikpe** [comment]
@ivanJoly I've updated the repo and included react-router-dom + a simple example of routing in the app. I didn't have to change any webpack configuration.
